import { iconWithClassName } from './icon-with-classname';

import HomeStroke from 'assets/images/icons/home-stroke.svg';
import HomeSolid from 'assets/images/icons/home-solid.svg';
import UserStroke from 'assets/images/icons/user-stroke.svg';
import UserSolid from 'assets/images/icons/user-solid.svg';
import SettingStroke from 'assets/images/icons/setting-stroke.svg';
import ArrowLeftStroke from 'assets/images/icons/arrow-left-stroke.svg';
import ArrowRightStroke from 'assets/images/icons/arrow-right-stroke.svg';
import GoogleStroke from 'assets/images/icons/google-stroke.svg';
import FacebookStroke from 'assets/images/icons/facebook-stroke.svg';
import AppleStroke from 'assets/images/icons/apple-stroke.svg';
import ViewStroke from 'assets/images/icons/view-stroke.svg';
import ViewOffSlashStroke from 'assets/images/icons/view-off-slash-stroke.svg';
import TickStroke from 'assets/images/icons/tick-stroke.svg';
import EditStroke from 'assets/images/icons/edit-stroke.svg';
import CrownSolid from 'assets/images/icons/crown-solid.svg';

iconWithClassName(HomeStroke);
iconWithClassName(HomeSolid);
iconWithClassName(UserStroke);
iconWithClassName(UserSolid);
iconWithClassName(SettingStroke);
iconWithClassName(ArrowLeftStroke);
iconWithClassName(ArrowRightStroke);
iconWithClassName(GoogleStroke);
iconWithClassName(FacebookStroke);
iconWithClassName(AppleStroke);
iconWithClassName(ViewStroke);
iconWithClassName(ViewOffSlashStroke);
iconWithClassName(TickStroke);
iconWithClassName(EditStroke);
iconWithClassName(CrownSolid);

export { HomeStroke };
export { HomeSolid };
export { UserStroke };
export { UserSolid };
export { SettingStroke };
export { ArrowLeftStroke };
export { ArrowRightStroke };
export { GoogleStroke };
export { FacebookStroke };
export { AppleStroke };
export { ViewStroke };
export { ViewOffSlashStroke };
export { TickStroke };
export { EditStroke };
export { CrownSolid };
