name: Build for Staging

on:
  push:
    branches:
      - release/*

jobs:
  build:
    uses: ./.github/workflows/build-eas.yml
    with:
      app-env: staging
      build-type: apk,ipa
      hostname: ${{ vars.HOSTNAME }}
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
