name: Build for Production

on:
  push:
    branches:
      - release/*

jobs:
  build:
    uses: ./.github/workflows/build-eas.yml
    with:
      app_env: production
      build_type: apk,aab,ipa
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
