name: Build for Production

on:
  push:
    branches:
      - release/*

jobs:
  build:
    uses: ./.github/workflows/build-eas.yml
    with:
      app-env: production
      build-type: apk,aab,ipa
      hostname: ${{ vars.HOSTNAME }}
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      EXPO_PUBLIC_SUPABASE_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_KEY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      EXPO_PUBLIC_REVENUECAT_API_KEY: ${{ secrets.EXPO_PUBLIC_REVENUECAT_API_KEY }}
      EXPO_PUBLIC_POSTHOG_API_KEY: ${{ secrets.EXPO_PUBLIC_POSTHOG_API_KEY }}
