name: Reusable Expo OTA Updates Workflow

on:
    workflow_call:
        inputs:
            app-env:
                description: 'Deployment environment (staging / production)'
                required: false
                default: 'production'
                type: string
            platform:
                description: 'android or ios'
                required: true
                type: string
            hostname:
                description: 'An API endpoint for uploading to Vercel blob storage'
                required: true
                type: string
        secrets:
            VERCEL_BLOB_READ_WRITE_TOKEN:
                description: 'An API access token for Vercel blob storage'

env:
    APP_ENV: ${{ inputs.app-env }}
    HOSTNAME: ${{ inputs.hostname }}
    VERCEL_BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_READ_WRITE_TOKEN }}

jobs:
    update:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js and dependencies
              uses: ./.github/actions/setup-node-and-deps

            - name: Export bundles
              run: pnpm exec expo export --platform ${{ inputs.platform }}

            - name: Copy expo config to dist
              run: pnpm exec expo config --json > dist/expoConfig.json

            - name: Get project fingerprint
              run: |
                  FINGERPRINT=$(pnpm exec expo-updates fingerprint:generate --platform ${{ inputs.platform }} | jq -r '.hash')
                  echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV

            - name: Get EAS project ID
              run: echo "PROJECT_ID=$(jq -r '.extra.eas.projectId' dist/expoConfig.json)" >> $GITHUB_ENV

            - name: Set update bundle path prefix
              run: |
                  if [ -n "$PROJECT_ID" ] && [ -n "$FINGERPRINT" ]; then
                    UPDATE_BUNDLE_PATH_PREFIX=$PROJECT_ID/${{ inputs.app-env }}/${{ inputs.platform }}/$FINGERPRINT
                    echo "UPDATE_BUNDLE_PATH_PREFIX=$UPDATE_BUNDLE_PATH_PREFIX" >> $GITHUB_ENV
                    echo "The update bundle path prefix is $UPDATE_BUNDLE_PATH_PREFIX"
                  fi

            - name: Compress and list files
              run: |
                  tar -czvf updates.tar.gz dist
                  ls -lh updates.tar.gz

            - name: Upload bundles to Vercel Blob Storage
              run: |
                  curl -X POST "$HOSTNAME/api/upload" \
                      -H "Authorization: Bearer $VERCEL_BLOB_READ_WRITE_TOKEN" \
                      -F "file=@updates.tar.gz" \
                      -F "path=$UPDATE_BUNDLE_PATH_PREFIX"
