name: Reusable Expo OTA Updates Workflow

on:
  workflow_call:
    inputs:
      app-env:
        description: 'Deployment environment (staging / production)'
        required: false
        default: 'production'
        type: string
      platform:
        description: 'android or ios'
        required: true
        type: string
      hostname:
        description: 'An API endpoint for uplading to Vercel blob storage'
        required: true
        type: string
    secrets:
      VERCEL_BLOB_READ_WRITE_TOKEN:
        description: 'An API acesss token for Vercel blob storage'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ inputs.app-env }}
      HOSTNAME: ${{ inputs.hostname }}
      VERCEL_BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_READ_WRITE_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if curl is installed
        run: |
          if ! command -v curl &> /dev/null; then
            echo "curl is not installed, installing now..."
            sudo apt-get update && sudo apt-get install -y curl
          else
            echo "curl is already installed"
          fi

      - name: Set up Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      - name: Exported bundles
        run: pnpm exec expo export --platform ${{ inputs.platform }}

      - name: Copy expo config to dist
        run: npx expo config --json > dist/expoConfig.json

      - name: Computed project fingerprint / rumtimeVersion
        run: |
          FINGERPRINT=$(pnpm exec expo-updates fingerprint:generate --platform ${{ inputs.platform }} | jq -r '.hash')
          echo "FINGERPRINT=$FINGERPRINT" >> $GITHUB_ENV

      - name: Get eas projectid
        run: echo "PROJECT_ID=$(jq -r '.extra.eas.projectId' dist/expoConfig.json)" >> $GITHUB_ENV

      - name: Get the update bundle path prefix
        if: ${{ env.PROJECT_ID != '' && env.FINGERPRINT != '' }}
        run: |
          UPDATE_BUNDLE_PATH_PREFIX=$PROJECT_ID/$APP_ENV/${{ inputs.platform }}/$FINGERPRINT
          echo "UPDATE_BUNDLE_PATH_PREFIX=$UPDATE_BUNDLE_PATH_PREFIX"  >> $GITHUB_ENV
          echo "The update bundle path prefix is $UPDATE_BUNDLE_PATH_PREFIX"

      - name: Compress and list files
        run: |
          tar -czvf updates.tar.gz dist
          ls -lh updates.tar.gz

      - name: Upload bundles to Vercel Blob Storage
        run: |
          echo "Uploading file..."
          curl -X POST "$HOSTNAME/api/upload" \
              -H "Authorization: Bearer $VERCEL_BLOB_READ_WRITE_TOKEN" \
              -F "file=@updates.tar.gz" \
              -F "path=$UPDATE_BUNDLE_PATH_PREFIX"
          echo "End of Uploading file."
