name: OTA Update for Staging

on:
  push:
    branches:
      - hotfix/*

jobs:
  android-update:
    uses: ./.github/workflows/ota-expo.yml
    with:
      channel: staging
      platform: android
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      UPDATES_HOSTNAME: ${{ secrets.UPDATES_HOSTNAME }}
      VERCEL_BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_READ_WRITE_TOKEN }}

  ios-update:
    uses: ./.github/workflows/ota-expo.yml
    with:
      channel: staging
      platform: ios
    secrets:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      UPDATES_HOSTNAME: ${{ secrets.UPDATES_HOSTNAME }}
      VERCEL_BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_READ_WRITE_TOKEN }}
