name: OTA Update for Production

on:
  push:
    branches:
      - hotfix/*

jobs:
  android-update:
    uses: ./.github/workflows/ota-expo.yml
    with:
      platform: android
      app-env: production
      hostname: ${{ vars.HOSTNAME }}
    secrets:
      VERCEL_BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_READ_WRITE_TOKEN }}

  ios-update:
    uses: ./.github/workflows/ota-expo.yml
    with:
      platform: ios
      app-env: production
      hostname: ${{ vars.HOSTNAME }}
    secrets:
      VERCEL_BLOB_READ_WRITE_TOKEN: ${{ secrets.VERCEL_BLOB_READ_WRITE_TOKEN }}
